swagger: "2.0"
info:
  version: "0.0.1"
  title: Shop Project
host: localhost:10010
basePath: /
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /shops:
    x-swagger-router-controller: shop_controller
    get:
      description: Shows list of shops
      operationId: getShops
      responses:
        "200":
          description: Listed shops
          schema:
            $ref: "#/definitions/ShopsResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      description: Creates new shop
      operationId: createShop
      parameters:
        - name: name
          in: formData
          description: Shop name
          required: true
          type: string
        - name: description
          description: Shop description
          in: formData
          type: string
        - name: city
          description: Shop city place
          type: string
          in: formData
        - name: address
          description: Shop street and number place
          type: string
          in: formData
      responses:
        "200":
          description: A shop added to list
          schema:
            $ref: "#/definitions/ShopResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
            
  /shops/{id}:
    x-swagger-router-controller: shop_controller
    get:
      description: Shows a shop
      operationId: getShop
      parameters:
        - name: id
          in: path
          description: Shop ID
          required: true
          type: string
      responses:
        "200":
          description: Valid request
          schema:
            $ref: "#/definitions/ShopResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    put:
      description: Modifies a shop
      operationId: modifyShop
      parameters:
        - name: id
          in: path
          description: Shop ID
          required: true
          type: string
        - name: name
          in: formData
          description: Shop name
          type: string
        - name: description
          description: Shop description
          in: formData
          type: string
        - name: city
          description: Shop city place
          type: string
          in: formData
        - name: address
          description: Shop street and number place
          type: string
          in: formData
      responses:
        "200":
          description: Success modified shop 
          schema:
            $ref: "#/definitions/ShopResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      description: Add product to shop
      operationId: createProduct  
      parameters:
        - name: name
          in: formData
          description: item name
          required: true
          type: string
        - name: description
          description: Shop description
          in: formData
          type: string
        - name: price
          description: Product price
          type: number
          in: formData
        - name: count
          description: Product count
          type: number
          in: formData
      responses:
        "200":
          description: A product added to shop
          schema:
            $ref: "#/definitions/ProductResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    delete:
      description: Deletes a shop with all associated items
      operationId: deleteShop
      parameters:
        - name: id
          in: path
          description: Shop ID
          required: true
          type: string
      responses:
        "200":
          description: Success deleted shop
          schema:
            $ref: "#/definitions/ShopsResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  
  /shops/{id}/{productID}:  
    x-swagger-router-controller: management_controller
    get:
      description: show product
      operationId: getProduct
      parameters:
        - name: id
          in: path
          description: Shop ID
          required: true
          type: string
        - name: productID
          in: path
          description: Product ID
          required: true
          type: string
      responses:
        "200":
          description: Success show product
          schema:
            $ref: "#/definitions/ProductResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    put:
      description: Modifies a product
      operationId: modifyProduct
      parameters:
        - name: id
          in: path
          description: Shop ID
          required: true
          type: string
        - name: productID
          in: path
          description: Product ID
          required: true
          type: string
        - name: name
          in: formData
          description: Product name
          type: string
        - name: description
          description: Product description
          in: formData
          type: string
        - name: price
          description: Product price
          type: number
          in: formData
        - name: count
          description: Product count
          type: number
          in: formData
      responses:
        "200":
          description: Success modified product
          schema:
            $ref: "#/definitions/ProductResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    delete:
      description: Deletes a product form shop
      operationId: deleteProduct
      parameters:
        - name: id
          in: path
          description: Shop ID
          required: true
          type: string
        - name: productID
          in: path
          description: Product ID
          required: true
          type: string
      responses:
        "200":
          description: Success deleted product from shop
          schema:
            $ref: "#/definitions/ShopResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  
  /swagger:
    x-swagger-pipe: swagger_raw
definitions:
  ShopsResponse:
    type: array
    items:
      $ref: "#/definitions/ShopResponse"
  
  ShopResponse:
    required:
      - id
      - name
    properties:
      id: 
        type: string
      name:
        type: string
      description:
        type: string
      city: 
        type: string
      address:
        type: string
      products:
        type: array
        items:
          $ref "#/definitions/ProductResponse"
  
  ProductResponse:
    required:
      - id
      - name
    properties:
      id:
        type: string
      name:
        type: string
      description:
        type: string
      price:
        type: number
      count: 
        type: number
               
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string